package secarma;

import jsyntaxpane.syntaxkits.PythonSyntaxKit;

/**
 * This is the GUI tab added into Burp.
 * This uses the PythonSyntaxKit to make prettier Python editing a thing.
 * @author cornerpirate
 */
public class PythonTab extends javax.swing.JPanel {

    /**
     * Creates new form PythonTab
     */
    public PythonTab(String py) {
        initComponents();
        python.setEditorKit(new PythonSyntaxKit());
        python.setText(py);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        python = new javax.swing.JEditorPane();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(python);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JEditorPane python;
    // End of variables declaration//GEN-END:variables
}
